### ISSUE TITLE
Syntax error can crash a worker

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/kit#463] opened 2023-11-12 00:23 UTC
This job code `fn(state => throw "ere");` can take down a worker! The implications aren't as bad given the new isolation and restarting, but we should still be able to catch these types of errors.

```
[SRV] ℹ 265d8fb9-9aa3-4f43-a6a6-8a3631cf70d4 :: attempt:log :: OK
[SRV] ℹ 265d8fb9-9aa3-4f43-a6a6-8a3631cf70d4 :: attempt:log :: OK
[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "#<Object>".] {
  code: 'ERR_UNHANDLED_REJECTION'
}
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by josephjclark** [comment] 2023-11-12 14:46
This is a really strange one because the worker has explicit unit tests around this: https://github.com/OpenFn/kit/blob/548dae346ea75ec5d7286eb79912497f987623b9/packages/ws-worker/test/reasons.test.ts#L96

```
test('fail: user error', async (t) => {
  const plan = createPlan({
    expression: 'export default [(s) => { throw "abort!"; }]',
  });

  const { reason } = await execute(plan);
  t.is(reason.reason, 'fail');
  t.is(reason.error_message, 'abort!');
  t.is(reason.error_type, 'UserError');
});
```

**Comment by josephjclark** [comment] 2023-11-12 14:51
Ah this is actually a syntax error - try this job code:
```
 fn(state => { throw "ere" })
```

Admittedly the syntax error should be caught and handled. I will update the issue title.

**Comment by josephjclark** [comment] 2023-11-13 10:53
Really struggling to reproduce this in tests. Syntax errors are triggering crashes as I expect. It's all working perfectly, dammit!

**Comment by josephjclark** [comment] 2023-11-13 14:56
So I've added more tests around this and run some manual ones and it's looking fine.

I wonder if I've accidentally fixed it in one of the other PRs.

I'll keep my eyes open of course but I'm going to close this ticket down. I'll be added more tests as I go through the hardening process this week.

**Closed by josephjclark** 2023-11-13 14:56 UTC
Labels: bug
